"""add image url to jobs

Revision ID: 2510f32dfc1a
Revises: a801d379ae24
Create Date: 2026-08-26 05:53:44.281146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2510f32dfc1a'
down_revision: Union[str, Sequence[str], None] = 'a801d379ae24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'image_url')
    # ### end Alembic commands ###
