"""add course registrations

Revision ID: d7de0fffbdbe
Revises: 1a9c2eb9f332
Create Date: 2026-09-01 07:24:30.866692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7de0fffbdbe'
down_revision: Union[str, Sequence[str], None] = '1a9c2eb9f332'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('course', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('other', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_registrations_email'), 'course_registrations', ['email'], unique=False)
    op.create_index(op.f('ix_course_registrations_id'), 'course_registrations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_course_registrations_id'), table_name='course_registrations')
    op.drop_index(op.f('ix_course_registrations_email'), table_name='course_registrations')
    op.drop_table('course_registrations')
    # ### end Alembic commands ###
