"""change blog author to admin

Revision ID: e68fa9da9fd5
Revises: b95f5873d9fc
Create Date: 2026-08-20 07:28:39.014164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e68fa9da9fd5'
down_revision: Union[str, Sequence[str], None] = 'b95f5873d9fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('admin_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('blogs_author_id_fkey'), 'blogs', type_='foreignkey')
    op.create_foreign_key(None, 'blogs', 'admins', ['admin_id'], ['id'])
    op.drop_column('blogs', 'author_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'blogs', type_='foreignkey')
    op.create_foreign_key(op.f('blogs_author_id_fkey'), 'blogs', 'users', ['author_id'], ['id'])
    op.drop_column('blogs', 'admin_id')
    # ### end Alembic commands ###
