"""change blog author to admin

Revision ID: e68fa9da9fd5
Revises: b95f5873d9fc
Create Date: 2026-08-20 07:28:39.014164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e68fa9da9fd5'
down_revision: Union[str, Sequence[str], None] = 'b95f5873d9fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # 1. Add admin_id as nullable first
    op.add_column(
        'blogs',
        sa.Column('admin_id', sa.Integer(), nullable=True)
    )

    # 2. Remove the old author foreign key
    op.drop_constraint(
        op.f('blogs_author_id_fkey'),
        'blogs',
        type_='foreignkey'
    )

    # 3. Add the foreign key for admin_id
    op.create_foreign_key(
        'blogs_admin_id_fkey',
        'blogs',
        'admins',
        ['admin_id'],
        ['id']
    )

    # 4. IMPORTANT:
    # Assign existing blogs to your admin.
    #
    # Change 1 below to the actual ID of your admin.
    op.execute(
        "UPDATE blogs SET admin_id = 1 WHERE admin_id IS NULL"
    )

    # 5. Now that existing blogs have an admin,
    # make admin_id required
    op.alter_column(
        'blogs',
        'admin_id',
        existing_type=sa.Integer(),
        nullable=False
    )

    # 6. Remove old author_id
    op.drop_column('blogs', 'author_id')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'blogs', type_='foreignkey')
    op.create_foreign_key(op.f('blogs_author_id_fkey'), 'blogs', 'users', ['author_id'], ['id'])
    op.drop_column('blogs', 'admin_id')
    # ### end Alembic commands ###
